#%RAML 1.0 NamedExample

value:
  total : 150
  currency: USD
  date: 2012-10-11T12:30:40-03:00
  customer:
      id : string
      city: string
      country: France
      postalCode: 95160
      email: test@gmail.com
      name: string
      phone: 01.02.03.90.16
  lineItems:
      id: 2
      amount: 5

