#%RAML 1.0
title: RAML_TP1

types: 
  Commands: !include commands_modules/commandType.raml
/commands:
  get:
    queryParameters:
      productName:
        required: false
      customerId:
        required: false
      orderBy: 
        required: false
        enum:
          - price
          - quantity
    responses: 
      200:
        body: 
          application/json:
            examples:
              output : !include /examples/CommandsExample.raml

  /{ID}:
    get:
      responses:
        200:
          body:
            application/json:
              examples : 
                output : !include /examples/CommandExample.raml
